# Generates a C++ header with the file's bytes as a raw string literal.
file(READ "${INPUT_FILE}" CONTENT)
set(CONTENT "// AUTOGENERATED. Do not edit.\n#pragma once\nnamespace Nebula {\nstatic const char* kEmbeddedHtml = R\"NEBULA_HTML(${CONTENT})NEBULA_HTML\";\n}\n")
file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
